"use client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { cn } from "@/lib/utils";
import { FileMusic, ListMusic, Music } from "lucide-react";
import { Montserrat } from "next/font/google";

const font = Montserrat({ weight: '600', subsets: ['latin'] });

const instructions = [
  {
    name: "1. Upload Content",
    avatar: FileMusic,
    title: "",
    describe: "Upload your .txt file or paste in material that you want to turn into a song. We will analyze the text and generate lyrics for you.",
  },
  {
    name: "2. Edit Lyrics and Select Genre",
    avatar: ListMusic,
    title: "",
    describe: "Edit the generated lyrics, select a genre of music, and give your song a name.",
  },
  {
    name: "3. Listen and Learn",
    avatar: Music,
    title: "",
    describe: "Listen to the song generated by you, download, and memorize in no time.",
  },
];

export const LandingContent = () => {
  return (
    <div className="px-10 pb-30 gap-2 space-y-20 flex flex-col">
      <div className="flex flex-row justify-center items-center space-x-12">
        <div className="w-full flex flex-col justify-center items-center">
          <div className = "flex flex-col mb-5">
          <div className = "flex flex-row space-x-4">
            <h2 className={cn("flex justify-center text-6xl font-bold text-white", font.className)}>Redefining </h2>
            <div className="flex flex-row">
              <h2 className={cn("flex justify-center text-6xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-600", font.className)}>Ed</h2>
              <h2 className={cn("flex justify-center text-6xl font-bold text-white", font.className)}>ucation</h2>
            </div>
          </div>
          <h2 className = {cn("text-slate-300 text-lg flex justify-center items-center", font.className)}> Quickly turn your studying material into a song in 3 easy steps </h2>
          </div>
          <div className="grid sm:grid-cols-1 sm:gap-y-2 lg:grid-cols-3 lg:gap-x-3 lg:w-full ">
            {instructions.map((item, index) => (
              <Card key={index} className="bg-[#192339] border-none text-white">
                <CardHeader>
                  <CardTitle className="flex items-center gap-x-2">
                    <div>
                      <div className = "pb-3">
                        <item.avatar />
                      </div>
                      <div>
                      <p className="text-2xl">{item.name}</p>
                      <p className="text-zinc-400 text-sm">{item.title}</p>
                      </div>
                    </div>
                  </CardTitle>
                  <CardContent className="pt-4 px-0 text-xl">
                    {item.describe}
                  </CardContent>
                </CardHeader>
              </Card>
            ))}
          </div>
        </div>
      </div>

      <br />
      <br />
      <br />
    </div>
  );
};
