"use client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { cn } from "@/lib/utils";
import { FileMusic, ListMusic, Music } from "lucide-react";
import { Montserrat } from "next/font/google";
import { CardBody, CardContainer, CardItem } from "@/components/ui/3d-card"
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from "@/components/ui/carousel"

const font = Montserrat({ weight: '600', subsets: ['latin'] });

const instructions = [
  {
    name: "1. Upload Content",
    avatar: FileMusic,
    title: "",
    describe: "Upload your .txt file or paste in material that you want to turn into a song. We will analyze the text and generate lyrics for you.",
  },
  {
    name: "2. Edit Lyrics and Select Genre",
    avatar: ListMusic,
    title: "",
    describe: "Edit the generated lyrics, select a genre of music, and give your song a name.",
  },
  {
    name: "3. Listen and Learn",
    avatar: Music,
    title: "",
    describe: "Listen to the song generated by you, download, and memorize in no time.",
  },
];

export const LandingContent = () => {
  return (
    <div className="px-10 pb-30 gap-2 space-y-20 flex flex-col">
      <div className="flex flex-row justify-center items-center space-x-12">
        <div className="w-full flex flex-col justify-center items-center">
          <div className="flex flex-col mb-5">
            <div className="flex flex-row space-x-4">
              <h2 className={cn("flex justify-center text-6xl font-bold text-white", font.className)}>Redefining </h2>
              <div className="flex flex-row">
                <h2 className={cn("flex justify-center text-6xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-600", font.className)}>Ed</h2>
                <h2 className={cn("flex justify-center text-6xl font-bold text-white", font.className)}>ucation</h2>
              </div>
            </div>
            <h2 className={cn("text-slate-300 text-lg flex justify-center items-center py-5", font.className)}> Quickly turn your studying material into a song in 3 easy steps </h2>
          </div>
          <div className="grid sm:grid-cols-1 sm:gap-y-2 lg:grid-cols-3 lg:gap-x-3 lg:w-full ">
            {instructions.map((item, index) => (
              <Card key={index} className="bg-[#192339] border-none text-white">
                <CardHeader>
                  <CardTitle className="flex items-center gap-x-2">
                    <div>
                      <div className="pb-3">
                        <item.avatar />
                      </div>
                      <div>
                        <p className="text-2xl">{item.name}</p>
                        <p className="text-zinc-400 text-sm">{item.title}</p>
                      </div>
                    </div>
                  </CardTitle>
                  <CardContent className="pt-4 px-0 text-xl">
                    {item.describe}
                  </CardContent>
                </CardHeader>
              </Card>
            ))}
          </div>
        </div>
      </div>
      <br />
      <br />
      <br />
      <div className="flex flex-row justify-center items-center">
        <div className="w-full flex flex-col justify-center items-center">
          <div className="flex flex-col">
            <h2 className={cn("flex justify-center text-6xl font-bold text-white", font.className)}>Demo </h2>
          </div>
          <div className = "flex justify-center relative">
          <Carousel>
            <CarouselContent>
              <CarouselItem>
                <CardContainer className="flex justify-center flex-center text-center">
                  <CardBody className={cn("bg-[#192339] border-black/[0.1] sm:w-[30rem] h-auto rounded-xl p-6 border", font.className)}>
                    <CardItem
                      as="p"
                      translateZ="100"
                      className="flex justify-center text-center text-white max-w-sm"
                    >
                      Watch a video demonstration of the beta
                    </CardItem>
                    <CardItem
                      translateZ="100"
                      rotateX={20}
                      rotateZ={-10}
                      className="w-full mt-4 flex justify-center"
                    >
                      <iframe width="430" height="250" src="https://www.youtube.com/embed/kGxIYlxJ5wo?si=arKIZ3on5noi_U3J" title="YouTube video player" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"></iframe>
                    </CardItem>
                    <div className="flex justify-end items-center mt-20">
                      
                      <CardItem
                        translateZ={20}
                        translateX={40}
                        as="button"
                        className=" px-4 py-2 rounded-xl bg-black dark:bg-white dark:text-black text-white text-xs font-bold"
                      >
                        Join Waitlist
                      </CardItem>
                    </div>
                  </CardBody>
                </CardContainer>
                </CarouselItem>
                <CarouselItem>
                <CardContainer className="flex justify-center flex-center text-center">
                  <CardBody className={cn("bg-[#192339] border-black/[0.1] sm:w-[30rem] h-auto rounded-xl p-6 border", font.className)}>
                    <CardItem
                      as="p"
                      translateZ="100"
                      className="flex justify-center text-center text-white max-w-sm"
                    >
                      Watch a video demonstration of the beta
                    </CardItem>
                    <CardItem
                      translateZ="100"
                      rotateX={20}
                      rotateZ={-10}
                      className="w-full mt-4 flex justify-center"
                    >
                      <iframe width="430" height="250" src="https://www.youtube.com/embed/kGxIYlxJ5wo?si=arKIZ3on5noi_U3J" title="YouTube video player" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"></iframe>
                    </CardItem>
                    <div className="flex justify-end items-center mt-20">
                      
                      <CardItem
                        translateZ={20}
                        translateX={40}
                        as="button"
                        className=" px-4 py-2 rounded-xl bg-black dark:bg-white dark:text-black text-white text-xs font-bold"
                      >
                        Join Waitlist
                      </CardItem>
                    </div>
                  </CardBody>
                </CardContainer>
                </CarouselItem>
            </CarouselContent>
            <CarouselPrevious className="absolute left-0 top-1/2 transform -translate-y-1/2" />
            <CarouselNext className="absolute right-0 top-1/2 transform -translate-y-1/2" />

            </Carousel>
          </div>
        </div>
      </div>
      <br />
      <br />
      <br />
    </div>
  );
};
